<?php

namespace DoctrineORMModule\Proxy\__CG__\IntelligenceArtificielle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Regle extends \IntelligenceArtificielle\Entity\Regle implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setProposition($proposition)
    {
        $this->__load();
        return parent::setProposition($proposition);
    }

    public function getProposition()
    {
        $this->__load();
        return parent::getProposition();
    }

    public function setVerbe($verbe)
    {
        $this->__load();
        return parent::setVerbe($verbe);
    }

    public function getVerbe()
    {
        $this->__load();
        return parent::getVerbe();
    }

    public function setNegative($negative)
    {
        $this->__load();
        return parent::setNegative($negative);
    }

    public function getNegative()
    {
        $this->__load();
        return parent::getNegative();
    }

    public function addConclusion(\IntelligenceArtificielle\Entity\Regle $conclusion)
    {
        $this->__load();
        return parent::addConclusion($conclusion);
    }

    public function removeConclusion(\IntelligenceArtificielle\Entity\Regle $conclusion)
    {
        $this->__load();
        return parent::removeConclusion($conclusion);
    }

    public function getConclusion()
    {
        $this->__load();
        return parent::getConclusion();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'proposition', 'verbe', 'negative', 'conclusion');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}